project:
  type: website

callout-icon: true
website:
  title: "KEPipedia"
  navbar:
    left:
      - text: Epidemiology
        href: content/epidemiology/index.qmd
      - text: Statistics
        href: content/statistics/index.qmd
      - text: Programming
        href: content/programming/index.qmd
      - text: Articles
        href: content/articles/index.qmd

highlight-style: github
format:
  html:
    monofont: "Fira Code"
    theme: 
      light: [flatly, assets/light.scss]
      dark: [darkly, assets/dark.scss]
    toc: true
